from pathlib import Path
ROOT = Path(__file__).parent.parent
ROOT_DIR = ROOT / 'files'
WINDOW_IMG_ICON = ROOT_DIR/ 'icon.png'

LARGE_FONT = 40
MEDIUM_FONT = 24
SMALL_FONT = 18
TEXT_MARGEN = 15
MINIMUN_WIDTH = 500

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#fff'